name: Pilipala Debug Build

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: 代码迁出
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 构建Java环境
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 强制锁定旧版插件依赖
        run: |
          echo "" >> pubspec.yaml
          echo "dependency_overrides:" >> pubspec.yaml
          echo "  dynamic_color: 1.6.8" >> pubspec.yaml
          echo "  font_awesome_flutter: 10.7.0" >> pubspec.yaml

      - name: 安装Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: 下载项目依赖
        run: flutter pub get

      - name: 自动修复 Android 编译版本限制
        run: |
          sed -i 's/compileSdkVersion .*/compileSdkVersion 36/g' android/app/build.gradle
          sed -i 's/compileSdk .*/compileSdk 36/g' android/app/build.gradle

      - name: 编译 Debug 版 APK (无须签名)
        run: flutter build apk --debug

      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: Pilipala-Debug-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
